AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/${RABBIT_VHOST:/}

# -------------------ğŸ‘‡ ä¸‹é¢æ˜¯ server ç›¸å…³çš„é…ç½® -----------------
amd5700g:
    rabbitmq:
        host: 192.168.31.245
        port: 5672
        username: pon
        password: pon
        vhost: /